name: spaceship
channels:
  - defaults
dependencies:
  - ca-certificates=2021.4.13=haa95532_1
  - certifi=2020.12.5=py39haa95532_0
  - openssl=1.1.1k=h2bbff1b_0
  - pip=21.0.1=py39haa95532_0
  - python=3.9.4=h6244533_0
  - setuptools=52.0.0=py39haa95532_0
  - sqlite=3.35.4=h2bbff1b_0
  - tzdata=2020f=h52ac0ba_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py39h2bbff1b_0
  - pip:
    - pygame==2.0.1
    - windows-curses==2.2.0
prefix: C:\Anaconda3\envs\spaceship
